export const CATEGORY = {
  USER: 'USER',
  NAVIGATION: 'NAVIGATION',
  VIEW_DOCUMENT: 'VIEW_DOCUMENT'
};

export const ACTION = {
  CLICK: 'CLICK'
};

export const LABEL = {
  SEND_CONTACT_MESSAGE: 'SEND_CONTACT_MESSAGE',
  NAV_BAR_ABOUT_ME: 'NAV_BAR_ABOUT_ME',
  NAV_BAR_ABOUT_CV: 'NAV_BAR_ABOUT_CV',
  NAV_BAR_PUBLICATIONS: 'NAV_BAR_PUBLICATIONS',
  NAV_BAR_CONTACT: 'NAV_BAR_CONTACT',
  NAV_BAR_BRAND: 'NAV_BAR_BRAND',
  ABOUT_ME_OVERVIEW_CONTACT: 'ABOUT_ME_OVERVIEW_CONTACT',
  JUMBOTRON_GET_TO_NO_ME: 'JUMBOTRON_GET_TO_NO_ME',
  JUMBOTRON_HIRE_ME: 'JUMBOTRON_HIRE_ME',
  SOCIAL_HEADING_GITHUB: 'SOCIAL_HEADING_GITHUB',
  SOCIAL_HEADING_LINKEDIN: 'SOCIAL_HEADING_LINKEDIN',
  SOCIAL_HEADING_TWITTER: 'SOCIAL_HEADING_TWITTER',
  SOCIAL_HEADING_GOOGLEPLUS: 'SOCIAL_HEADING_GOOGLEPLUS',
  FOOTER_GITHUB: 'FOOTER_GITHUB',
  FOOTER_LINKEDIN: 'FOOTER_LINKEDIN',
  FOOTER_TWITTER: 'FOOTER_TWITTER',
  FOOTER_GOOGLEPLUS: 'FOOTER_GOOGLEPLUS',
  FOOTER_COPYWRITE_BUTTON: 'FOOTER_COPYWRITE_BUTTON'
};
